"""add processed whatsapp messages

Revision ID: 57f88cf9ee63
Revises: 88d85f44fb7d
Create Date: 2026-09-26 23:47:19.639405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f88cf9ee63'
down_revision: Union[str, Sequence[str], None] = '88d85f44fb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_whatsapp_messages',
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_whatsapp_messages')
    # ### end Alembic commands ###
